import { DailyChallenge, todayUtc } from "../domain/daily/DailyChallenge.ts";
import { Game } from "../domain/game/Game.ts";
import { DomainError } from "../domain/shared/DomainError.ts";
import {
  DailyChallengeRepository,
  DuplicateDailyEntry,
} from "../ports/DailyChallengeRepository.ts";
import { WordRepository } from "../ports/WordRepository.ts";

export interface PlayDailyInput {
  userId: string | null;
  /**
   * Required for anonymous players: a stable per-install UUID generated by the
   * client. Used as the `games.id` for their daily entry so the same anon
   * user gets the same game back on later calls. Ignored if userId is set.
   */
  anonymousId?: string;
}

export interface PlayDailyOutput {
  challenge: DailyChallenge;
  game: Game;
  alreadyPlayed: boolean;
}

/**
 * Idempotent: first call creates the challenge (if needed) and the user's
 * game; subsequent calls return the same game so the UI can restore state.
 */
export class PlayDailyChallenge {
  constructor(
    private readonly daily: DailyChallengeRepository,
    private readonly words: WordRepository,
    private readonly clock: () => Date = () => new Date(),
  ) {}

  async execute(input: PlayDailyInput): Promise<PlayDailyOutput> {
    if (input.userId == null && !input.anonymousId) {
      throw new DomainError(
        "INVALID_INPUT",
        "Anonymous play requires X-Anonymous-Id header",
      );
    }

    const day = todayUtc(this.clock());

    const challenge = await this.daily.findOrCreate(day, async (length) => {
      return await this.words.randomWord(length);
    });

    const existing = input.userId != null
      ? await this.daily.findUserGame(day, input.userId)
      : await this.daily.findAnonymousGame(day, input.anonymousId!);
    if (existing) {
      return { challenge, game: existing, alreadyPlayed: true };
    }

    const newGame = Game.create({
      id: input.userId != null ? crypto.randomUUID() : input.anonymousId!,
      ownerId: input.userId,
      secretWord: challenge.secretWord,
      wordLength: challenge.wordLength,
      maxAttempts: challenge.maxAttempts,
    });

    try {
      const persisted = await this.daily.insertDailyGame(newGame, day);
      return { challenge, game: persisted, alreadyPlayed: false };
    } catch (e) {
      if (e instanceof DuplicateDailyEntry) {
        // A concurrent request beat us — re-fetch and return the winning row.
        const reloaded = input.userId != null
          ? await this.daily.findUserGame(day, input.userId)
          : await this.daily.findAnonymousGame(day, input.anonymousId!);
        if (reloaded) {
          return { challenge, game: reloaded, alreadyPlayed: true };
        }
      }
      throw e;
    }
  }
}
